name: RevoBank API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: run.py
      FLASK_ENV: testing
      SECRET_KEY: test_key
      JWT_SECRET_KEY: test_jwt_key

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest pytest-flask
        pip install -r requirements.txt
        
    - name: Test app creation
      run: |
        python -c "from app import create_app; app = create_app('testing'); print('App created successfully')"

    - name: Run basic test
      run: |
        python -c "
        from app import create_app
        app = create_app('testing')
        with app.test_client() as client:
            response = client.get('/')
            assert response.status_code in [404, 200]
            print('Basic test passed!')
        "
