name: RevoBank API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: run.py
      FLASK_ENV: testing
      SECRET_KEY: test_key
      JWT_SECRET_KEY: test_jwt_key

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create test directory
      run: |
        mkdir -p tests
        touch tests/__init__.py
        
    - name: Create basic test
      run: |
        echo 'def test_app_exists(client):
            assert client is not None' > tests/test_basic.py
        
    - name: Run tests
      run: |
        pytest tests/ -v

    - name: Build Docker image
      run: |
        echo "FROM python:3.9-slim
        WORKDIR /app
        COPY . .
        RUN pip install -r requirements.txt
        CMD [\"gunicorn\", \"run:app\"]" > Dockerfile
        docker build -t revobank-api .
      
    - name: Run security scan
      run: |
        # Basic security checks
        pip install bandit
        bandit -r app/

  # Deployment step will depend on your chosen platform
  # Examples: Railway, Render, DigitalOcean, AWS, etc.
